"""
Noise Inconsistency and High-Frequency Residual Analysis Module.

Authentic digital photos have a consistent noise floor generated by the camera's
sensor (ISO, PRNU, shot noise). Spliced elements, localized inpainting, or denoised
regions exhibit severe local noise variance and entropy disparities.
"""
from typing import Any, Dict, Tuple
import cv2
import numpy as np
from scipy.ndimage import median_filter

from app.config import NoiseConfig, DEFAULT_CONFIG
from app.utils.visualizer import create_heatmap, normalize_to_uint8


class NoiseDetector:
    """Analyzes high-frequency noise residuals to detect splicing and inpainting anomalies."""

    def __init__(self, config: NoiseConfig = DEFAULT_CONFIG.noise):
        self.config = config

    def extract_noise_residual(self, gray_img: np.ndarray) -> np.ndarray:
        """
        Extracts high-pass noise residuals using median filtering subtraction
        and Laplacian edge suppression.
        """
        gray_float = gray_img.astype(np.float32)
        # Median filter residual
        denoised = median_filter(gray_float, size=self.config.filter_kernel_size)
        residual = gray_float - denoised

        # Suppress strong structural edges to isolate pure sensor noise
        sobelx = cv2.Sobel(gray_float, cv2.CV_32F, 1, 0, ksize=3)
        sobely = cv2.Sobel(gray_float, cv2.CV_32F, 0, 1, ksize=3)
        edge_mag = np.sqrt(sobelx**2 + sobely**2)
        
        edge_threshold = np.percentile(edge_mag, 85)
        edge_mask = edge_mag > edge_threshold
        residual[edge_mask] *= 0.2  # Downweight structural edges

        return residual

    def analyze(self, image_rgb: np.ndarray) -> Dict[str, Any]:
        """
        Analyzes noise consistency across spatial patches of the image.

        Returns:
            Dict containing:
                score_percentage (float): Tampering likelihood score (0 to 100%)
                details (str): Forensic interpretation
                metrics (dict): Global noise floor, outlier ratio, variance IQR, etc.
                residual_map (np.ndarray): High-pass noise residual (uint8 normalized)
                heatmap_rgb (np.ndarray): Noise inconsistency heatmap (uint8)
        """
        h, w, _ = image_rgb.shape
        gray = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2GRAY)

        # 1. Extract noise residual
        residual = self.extract_noise_residual(gray)

        # 2. Patch-based noise variance estimation
        patch_size = self.config.patch_size
        stride = patch_size // 2  # Overlapping sliding window

        patch_stds = []
        patch_coords = []
        anomaly_grid = np.zeros((h, w), dtype=np.float32)
        count_grid = np.zeros((h, w), dtype=np.float32)

        for y in range(0, h - patch_size + 1, stride):
            for x in range(0, w - patch_size + 1, stride):
                p_res = residual[y : y + patch_size, x : x + patch_size]
                # Standard deviation as local noise floor
                std_val = float(np.std(p_res))
                patch_stds.append(std_val)
                patch_coords.append((y, x))

        patch_stds = np.array(patch_stds, dtype=np.float32)

        if len(patch_stds) == 0:
            # Fallback for very small images
            patch_stds = np.array([float(np.std(residual))])
            median_std = float(patch_stds[0])
            mad = 1.0
            outlier_ratio = 0.0
            max_z = 0.0
        else:
            # 3. Robust Statistics (Median and MAD)
            median_std = float(np.median(patch_stds))
            # Median Absolute Deviation (MAD)
            mad = float(np.median(np.abs(patch_stds - median_std))) * 1.4826
            mad = max(mad, 1e-5)

            # Compute z-scores for all patches
            z_scores = np.abs(patch_stds - median_std) / mad
            max_z = float(np.max(z_scores))
            
            # Significant outlier patches exceeding MAD threshold
            outliers = z_scores > self.config.mad_threshold
            outlier_ratio = float(np.sum(outliers) / len(z_scores))

            # Accumulate spatial anomaly map
            for idx, (y, x) in enumerate(patch_coords):
                z_val = z_scores[idx]
                anomaly_grid[y : y + patch_size, x : x + patch_size] += z_val
                count_grid[y : y + patch_size, x : x + patch_size] += 1.0

        count_grid[count_grid == 0] = 1.0
        anomaly_map = anomaly_grid / count_grid

        # 4. Tampering Score Calculation (0 to 100%)
        # Natural scenes have mild noise fluctuations between shadow and highlight regions.
        # Spliced regions with different ISO/sensor profiles have extreme Z-scores (>5.0) and outlier ratios (>10%).
        score = 0.0

        # Outlier proportion component with baseline tolerance (ignore outlier ratio below 0.04)
        effective_outlier_ratio = max(0.0, outlier_ratio - 0.04)
        score += min(55.0, (effective_outlier_ratio / 0.14) * 55.0)

        # Peak anomaly magnitude component (ignore Z-scores below 4.0)
        if max_z > 4.0:
            score += min(35.0, ((max_z - 4.0) / 8.0) * 35.0)

        # Variance coefficient of noise levels
        if len(patch_stds) > 1:
            noise_cv = float(np.std(patch_stds) / (median_std + 1e-6))
            effective_noise_cv = max(0.0, noise_cv - 0.25)
            score += min(10.0, (effective_noise_cv / 0.45) * 10.0)
        else:
            noise_cv = 0.0

        score_percentage = float(np.clip(round(score, 1), 0.0, 100.0))

        # 5. Descriptive Details
        if score_percentage > 70.0:
            details = (
                f"Severe noise variance anomaly detected (Peak MAD Z-score: {max_z:.2f}, "
                f"Outlier Ratio: {outlier_ratio*100:.1f}%). Highly heterogeneous noise residuals "
                f"indicate foreign object insertion or regional filtering/inpainting."
            )
        elif score_percentage > 35.0:
            details = (
                f"Moderate noise inconsistency observed (Median noise std: {median_std:.2f}, "
                f"Z-score: {max_z:.2f}). Local high-frequency variations suggest potential retouching."
            )
        else:
            details = (
                f"Consistent sensor noise floor throughout the image (Median std: {median_std:.2f}, "
                f"MAD: {mad:.2f}). No significant noise splicing detected."
            )

        # 6. Normalize residual and create heatmap
        norm_anomaly = normalize_to_uint8(anomaly_map)
        heatmap_rgb = create_heatmap(norm_anomaly, cv2.COLORMAP_INFERNO)
        residual_uint8 = normalize_to_uint8(np.abs(residual))

        return {
            "score_percentage": score_percentage,
            "details": details,
            "metrics": {
                "median_noise_std": round(median_std, 3),
                "noise_mad": round(mad, 3),
                "max_z_score": round(max_z, 2),
                "outlier_patch_ratio": round(outlier_ratio, 4),
                "noise_cv": round(noise_cv, 3),
            },
            "residual_map": residual_uint8,
            "heatmap_rgb": heatmap_rgb,
        }
